version: '3.8'

services:
  frontend:
    image: ck-loan-frontend:prod
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: loan_frontend_prod
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    image: ck-loan-backend:prod
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: loan_backend_prod
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - .env
